# Generated by Django 4.2.4 on 2023-08-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
